- name: This sets up an httpd webserver
  hosts: aws_ec2
  become: yes
  remote_user: ec2-user
  gather_facts: true
  vars:
    ansible_ssh_private_key_file: "/etc/ansible/key-from-jenkins.pem"  
    ansible_ssh_user: "ec2-user"
  tasks:
  - name: "Install httpd packages"
    package:
        name:
          - "httpd"
        state: present
  - name: "Create a simple HTML file"
    copy:
      content: |
        <!DOCTYPE html>
        <html>
        <head>
            <title>Welcome Page</title>
        </head>
        <body>
            <h1>Hello, This is Raphael!</h1>
            <p>Welcome to my Apache web server.</p>
        </body>
        </html>
      dest: /var/www/html/index.html
      owner: apache
      group: apache
      mode: '0644'
  - name: "Start httpd services"
    service:
      name: httpd
      state: started
  - name: Yum Install Packages
    yum: name={{item}} state=latest
    with_items:
       - wget
  - name: terraform install
    unarchive:
      src: https://releases.hashicorp.com/terraform/0.9.1/terraform_0.9.1_linux_amd64.zip
      dest: /usr/bin
      remote_src: True
